import { readFile, writeFile, readdir } from "node:fs/promises";
import path from "node:path";

export interface EnvDoctorOptions {
  dir?: string;
  envExamplePath?: string;
  sync?: boolean;
}

export interface EnvDoctorResult {
  referenced: string[];
  exampleVars: string[];
  missing: string[];
  synced: boolean;
}

/**
 * Recursively scans for code files in a directory.
 */
async function getFilesRecursively(dir: string): Promise<string[]> {
  const files: string[] = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return files;
  }

  for (const entry of entries) {
    const res = path.resolve(dir, entry.name);
    if (entry.name === "node_modules" || entry.name.startsWith(".") || entry.name === "dist") {
      continue;
    }
    if (entry.isDirectory()) {
      files.push(...(await getFilesRecursively(res)));
    } else {
      if (/\.(ts|js|tsx|jsx|mjs|cjs)$/.test(entry.name)) {
        files.push(res);
      }
    }
  }
  return files;
}

/**
 * Scans code files for process.env.VARIABLE references and audits/synchronizes with .env.example.
 */
export async function doctorEnv(options: EnvDoctorOptions = {}): Promise<EnvDoctorResult> {
  const dir = options.dir || process.cwd();
  const envExamplePath = options.envExamplePath || path.resolve(dir, ".env.example");
  const sync = options.sync !== undefined ? options.sync : false;

  const files = await getFilesRecursively(dir);
  const envVarRegex = /\bprocess\.env\.([A-Za-z0-9_$]+)\b/g;
  const referencedSet = new Set<string>();

  for (const file of files) {
    try {
      const content = await readFile(file, "utf8");
      let match;
      envVarRegex.lastIndex = 0;
      while ((match = envVarRegex.exec(content)) !== null) {
        referencedSet.add(match[1]);
      }
    } catch {}
  }

  const referenced = Array.from(referencedSet).sort();

  const exampleVars: string[] = [];
  let exampleContent = "";
  try {
    exampleContent = await readFile(envExamplePath, "utf8");
    const lines = exampleContent.split(/\r?\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith("#")) {
        const parts = trimmed.split("=");
        if (parts[0]) {
          exampleVars.push(parts[0].trim());
        }
      }
    }
  } catch {}

  const missing = referenced.filter((v) => !exampleVars.includes(v));
  let synced = false;

  if (sync && missing.length > 0) {
    let appendText = "";
    if (exampleContent && !exampleContent.endsWith("\n")) {
      appendText += "\n";
    }
    if (!exampleContent.includes("# Auto-generated by auto-env-doctor")) {
      appendText += "\n# Auto-generated by auto-env-doctor\n";
    }
    for (const m of missing) {
      appendText += `${m}=\n`;
    }
    try {
      await writeFile(envExamplePath, exampleContent + appendText, "utf8");
      synced = true;
    } catch {}
  }

  return {
    referenced,
    exampleVars,
    missing,
    synced,
  };
}
